1. Numpy N-Dimensional Array
    - 넘파이의 ndarray 라고 칭함
    - < 빠르지만 제약조건이 있음 >
        - 1. 모든 원소가 같은 자료형이어야 한다.
        - 2. 원소의 갯수를 바꿀 수 없다. 

-     *   배열의 차원과 크기 알아내기

In [3]:
import numpy as np

- ndarray (리스트 방식과 비교)

In [4]:
# 리스트 방식(기존)
l = [1, 2, 3, 4, 5]
l = [i * i for i in l]
l

[1, 4, 9, 16, 25]

In [5]:

n = np.array([1, 2, 3, 4, 5], dtype = int)  # 리스트 넣기 가능
n

array([1, 2, 3, 4, 5])

In [6]:
n = np.square(n)    # operation 한 번이면 모든 element에 적용됨
n

array([ 1,  4,  9, 16, 25])

- 1차원 배열(Vector) 만들기

In [7]:
a = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10))   # 튜플 넣기 가능
type(a)

numpy.ndarray

In [8]:
# 속성값 - 용어 알아두기
a.dtype # (dtype('int32') 정수
a.shape # (10,)
a.ndim # 1
a.size # 10 element개수

10

In [9]:
# 백터화 연산 *for반복문 없이 2배 연산 가능
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = 2*a+b
c

array([12, 24, 36])

In [11]:
# element에 대한 T/F 확인
a == 2  # array([False,  True, False])  a가 2와 같나?
b > 10  # array([False,  True,  True]) b가 10보다 큰가?

array([False,  True,  True])

- 2차원 배열(Matrix) : 표작업

In [12]:
# LV.1
c = np.array([[1,2,3],[4,5,6]])     # np.arange(1, 7).reshape(2, 3)
c
print(c)     # 어레이가 빠진 출력 버전

[[1 2 3]
 [4 5 6]]


In [13]:
# 2차원 배열 타입 확인
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor) : 이미지

In [14]:
t = np.arange(1, 25).reshape(2, 3, 4)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [15]:
# 
t.dtype, t.shape, t.ndim, t.size

(dtype('int32'), (2, 3, 4), 3, 24)

- 4차원 : 이미지 여러장, 동영상, ...

- ### 배열의 인덱싱
    - 리스트에서는 행과 열로 동시에 슬라이싱이 불가하다.

In [16]:
# 리스트 방식
a

array([1, 2, 3])

In [17]:
a[0], a[2], a[-1]

(1, 3, 3)

In [18]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c[0][0], c[-1,0], c[1,2]

(1, 4, 6)

- 배열의 슬라이싱 - 리스트에서는 불가

In [20]:
# 리스트 예 
l = [[1,2,3],[4,5,6],[7,8,9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [21]:
# 리스트에서는 행과 열로 동시에 슬라이싱이 불가하다.
l[:2][1:]

[[4, 5, 6]]

In [22]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
c = np.arange(1, 10).reshape(3, 3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
# 위에 두 행
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
# 오른쪽 두 열
c[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [26]:
# 5, 6, 8, 9
c[1:, 1:]

array([[5, 6],
       [8, 9]])

In [27]:
# 1, 4, 3, 6 찾기
c[:-1, ::2]

array([[1, 3],
       [4, 6]])

In [42]:
# 1 7 3 9
c[::2, ::2]

array([[1, 3],
       [7, 9]])

- 연습문제 2
    - 1. 이 행렬에서 값 7 을 인덱싱한다.
    - 2. 이 행렬에서 값 14 을 인덱싱한다.
    - 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
    - 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
    - 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [29]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [30]:
m[1, 2]   # 값 7 인덱싱
m[-1:, -1]  # 값 14 인덱싱

array([14])

In [31]:
m[1, 1:3]   # 배열[6, 7] 슬라이싱

m[1:, 2]    # 배열[7, 12] 슬라이싱

m[:-1, 3:]   # 배열 [[3, 4], [8, 9]]슬라이싱

array([[3, 4],
       [8, 9]])

In [32]:
m[:2, 3:]   # 배열 [[3, 4], [8, 9]]슬라이싱

array([[3, 4],
       [8, 9]])

- 배열 인덱싱(Fancy indexing)
    - True/False 필터
    - 인덱싱

In [33]:
# [idx] 필터 -True의 인덱싱 값만 걸러서 값 출력
a = np.array([1,2,3,4,5,6,7,8,9,10])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
# element 개수를 동일하게 써야 오류안 남
a[idx]

array([1, 3, 5, 7, 9])

In [34]:
a % 2 ==1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [35]:
a[a%2 ==1]

array([1, 3, 5, 7, 9])

In [36]:
# idx값이 정수값(인덱스)이면 해당 인덱스의 원소 출력
idx = np.array([1,3,5,7,9]) # a배열의 인덱싱값
a[idx]  

array([ 2,  4,  6,  8, 10])

- 연습문제 3
    - 이 배열에서 3의 배수를 찾아라.
    - 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
    - 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
    - * ndarray 출력 vw 스칼라 값으로 출력

In [37]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
# 이 배열에서 3의 배수를 찾아라.
x[x % 3 == 0]
# print(x[x % 3 == 0])

array([ 3,  6,  9, 12, 15, 18])

In [39]:
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [40]:
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

# 1) ndarray로 결과 출력
x[(x % 3==0) & (x % 4 == 1)]    # 9

# 2) 스칼라 값으로 출력
x[8], x[(x % 3==0) & (x % 4 == 1)][0]

(9, 9)