### 3. 배열의 연산(Operation)

In [1]:
import numpy as np

- 벡터화 연산 (vectorized operation)
    - 반복문을 사용하지 않고도 배열의 모든 원소에 대해 반복연산을 할 수 있다.
    - 사칙연산, 비교논리 연산 모두 가능
    - 지수함수, 로그함수 등 수학함수도 가능
    - * 리스트에서는 안됐던 기능

In [2]:
x = np.arange(1, 101)       # 1 2 3 4 5 ...100
y = np.arange(1101, 1201)   # 1101, 1102, 1103 ... 1200
z = x + y               # 1 + 1101, 2 + 1102, 3 + 1103 ...100 + 1200
z[:5]

array([1102, 1104, 1106, 1108, 1110])

In [3]:
z = 3 * x
z[:5]

array([ 3,  6,  9, 12, 15])

In [4]:
a =  np.array([1,2,3, 4])
b =  np.array([4,2,2, 4])
a == b

array([False,  True, False,  True])

In [5]:
a / b

array([0.25, 1.  , 1.5 , 1.  ])

In [6]:
a > b

array([False, False,  True, False])

In [7]:
np.log(a), np.exp(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [8]:
c = np.arange(6).reshape(2, 3)
np.exp(c)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [ ]:
# 스칼라의 덧셈
c + 3

- 차원 축소 연산
    - sum : 함수 np.sum()방식과 메소드 x.sum() 방식 두가지로 모두 가능

In [9]:
x = np.arange(1, 5) # 1~4
np.sum(x)   # 넘파이 함수로 sum

10

In [ ]:
x.sum()     # 넘파이 객체의 메소드로 sum

In [10]:
x.min(), x.max() # 최대, 최소

(1, 4, 2.5)

In [11]:
# 대표값:
x.mean(), np.median(x)

(2.5, 2.5)

- all or any

In [12]:
# all
np.all(np.array([True, False, True]))       # 모든 원소가 참이냐?

False

In [13]:
# any
np.any(np.array([True, False, True]))       # 하나라도 참인 원소가 있느냐?

True

- 2차원 이상의 연산

In [14]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# 모든 원소의 합/평군
np.sum(a), np.mean(a)

(21, 3.5)

In [19]:
# 행 방향으로 합/평균
np.sum(a, axis = 0), np.mean(a, axis = 0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [20]:
# 열 방향으로 합
np.sum(a, axis=1), np.mean(a, axis = 1)

(array([ 6, 15]), array([2., 5.]))

- argmax, argmin : 최대최소값을 인덱스값으로 출력

In [28]:
x = np.array([3, 12, 33, 9, 51, 26])
np.argmax(x), np.argmin(x)  # 최대최소값을 인덱스값으로 출력

(4, 0)

In [29]:
y = x.reshape(2, 3)
np.argmax(y, axis=0), np.argmin(y, axis = 0)

(array([1, 1, 0], dtype=int64), array([0, 0, 1], dtype=int64))

- 3.3.1 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
    -       * axis로 행열 계산할 때는 결과 값 반드시 확인(원래 행열 개수 == 값 개수)

In [51]:
m = np.arange(1, 31).reshape(5, 6).astype(float)    # .astype() 타입바꾸기
m

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [56]:
# 다른 방법으로 해보기
# random모듈 사용
np.random.seed(2023)    # 난수생성하는 seed값과 번호(0이상의 정수 입력)
np.set_printoptions(precision=4, suppress=True) # 소수점 자리수 4개로 끊음

m = np.random.random(30).reshape(5, 6)
m

array([[0.322 , 0.8904, 0.5881, 0.1266, 0.1413, 0.4679],
       [0.0221, 0.7273, 0.5244, 0.5449, 0.4564, 0.5014],
       [0.3945, 0.1512, 0.3609, 0.1621, 0.338 , 0.1803],
       [0.391 , 0.0356, 0.5649, 0.2035, 0.3206, 0.3766],
       [0.1841, 0.104 , 0.4549, 0.1959, 0.3785, 0.9305]])

In [ ]:
# 각 열의 최솟값
np.min(m, axis =0)

In [64]:
# 전체의 최댓값 

np.max(m)   # 기본
np.round(np.max(m), 4)  # round함수로 소수점 4자리까지

0.9305

In [75]:
# 전체의 최댓값
np.max(m)
np.round(np.max(m), 4)

0.9305

In [73]:
# 각 행의 합 = 열 방향으로 합*
np.sum(m, axis =1)
np.round(np.sum(m, axis =1), 4)

array([2.5363, 2.7764, 1.5869, 1.8921, 2.2479])

In [67]:
# 각 행의 최댓값
np.max(m, axis=1)

array([0.8904, 0.7273, 0.3945, 0.5649, 0.9305])

In [ ]:
# 각 열의 평균
np.mean(m, axis=0)  # 열은 6개니 값도 6개 나와야 함