In [1]:
import numpy as np

In [5]:
np.random.seed(2023)
np.random.random(5) # random이지만 seed번호(시작값) 지정

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링 (데이터 가져오는 것)

In [9]:
np.random.choice(5, 5, replace=False)

array([4, 2, 1, 0, 3])

In [10]:
x = np.random.randint(1, 100, 10)
x

array([50, 50, 50, 54, 39, 71, 16, 89, 73, 48])

In [11]:
np.random.choice(x, 5, replace=False)

array([50, 54, 50, 73, 48])

- 난수 생성

In [12]:
# random() : Uniform 분포, 0~1 사이의 값
np.random.random(10)

array([0.09702613, 0.81625998, 0.02808046, 0.01545164, 0.56690572,
       0.59310305, 0.9147945 , 0.25066314, 0.07173657, 0.30121014])

In [13]:
# randint(low, high, N) : [low, high)
# low<= x < high에서 포함은 [, 미포함은 )로 표시 
np.random.randint(1, 7, 10)

array([5, 4, 4, 1, 6, 4, 2, 6, 3, 4])

In [14]:
# normal(평균, 표준편차, N) - 정규분포
np.random.normal(170, 10, 10)

array([156.89599302, 176.76839882, 158.92016878, 184.48954679,
       159.75379517, 180.52417547, 177.7632241 , 178.26794973,
       172.40028585, 188.98243469])

In [15]:
# randn(N) - 표준정규분포 N(0, 1)
np.random.randn(10)

array([ 0.36683324,  0.81473231,  0.07235438,  0.6012461 , -1.727901  ,
        0.23404311, -0.01310212, -1.44489043, -1.29733638, -2.03158937])

In [16]:
# binomi(시도횟수, 평균, N) - 이항분포 B(N, p)
# ex 동전던지기(앞면이 나올 확률은 던지는 횟수가 증가할 수록 평균 0.5(50%확률)에 수렴)
np.random.binomial(10, 0.5, 20).reshape(4, 5)


array([[8, 7, 2, 4, 6],
       [4, 3, 6, 4, 5],
       [2, 4, 6, 7, 2],
       [6, 6, 5, 6, 5]])

# 가설 검정: t - 검정
# 우유 1000ml로  원샘플t
# 지금과 20년 전 7세 아동의 키 비교: 투샘플 t 
# 두 약으로 전후비교 : 페어드 t 테스트

In [17]:
# 가설 검정: t - 검정
# standard_t(자유도 ,N)
np.random.standard_t(2, 10) # 자유도 2, 값 10개 출력

array([-0.53206837, -0.22784308, -2.06707851,  0.97846344,  1.03677625,
       -1.63268272, -0.9087145 ,  3.46933835, -0.46213729, -0.21273215])

```{admonition} 연습 문제 3.5.1
1. 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
```

In [21]:
np.random.binomial(1, 0.5, 10)  # 1번 던질 때 0.5확률일 때 10번 던진 결과

array([0, 0, 0, 0, 1, 0, 1, 1, 1, 0])

```{admonition} 연습 문제 3.5.1
2. 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.
```

In [26]:
# randint(low, high, N)
np.mean(np.random.randint(1, 7, 100))   # 1~6의 수를 100번 돌린 값의 평균


3.53

```
가격이 10,000원인 주식이 있다.
이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
250일 동안의 주가를 무작위로 생성하라
**힌트
정규분포 : normal(평균, 표준편차, N)
기대값 0% = 평균 0.01 
```

In [35]:
# 1) 5개만 먼저 테스트하기
rate = np.random.normal(0, 0.01, 5)
rate

array([-0.00308421, -0.00128917, -0.01824254,  0.01289619, -0.00371933])

In [37]:
price = 10000
price = price + price * rate[0] # price * (1 + rate[0])
int(np.round(price))

9969

In [39]:
price = 10000
for i in range(5):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    print(price, end=' ')

9969 9956 9774 9900 9863 

In [40]:
# list로 해결
np.random.seed(2023)
rate = np.random.normal(0, 0.01, 250)
rate[:5]

array([ 0.00711674, -0.00324485, -0.01001871,  0.00236251, -0.0010216 ])

In [42]:
# list로 해결
price = 10000
price_list = []
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_list.append(price)

price_array = np.array(price_list)
price_array[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

In [44]:
# 2. array로 해결
price_array2 = np.zeros(250, dtype=int)
price = 10000
for i in range(250):
    price = price * (1 + rate[i])
    price = int(np.round(price))
    price_array2[i] = price

price_array2[-10:]

array([10814, 10893, 10674, 10645, 10588, 10724, 10739, 10686, 10691,
       10497])

- 데이터 카운팅(정수)

```연습 문제
주사위의 결과값의 평균 구하기
```

In [46]:
dices = np.random.randint(1, 7, 100)
np.unique(dices)    # 데이터에서 unique(고유한 값) 몇개?

array([1, 2, 3, 4, 5, 6])

In [56]:
indices, count = np.unique(dices, return_counts=True)
indices, count


(array([1, 2, 3, 4, 5, 6]), array([13, 28, 17, 13, 13, 16], dtype=int64))

In [62]:
d1= indices * count
np.sum(d1) / np.sum(count)

3.33

In [64]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [65]:
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [67]:
# xxx잘 활용 안 함 xxx
np.bincount(dices, minlength=6)

array([ 0, 13, 28, 17, 13, 13, 16], dtype=int64)